[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/eb/*"
  to = "/.netlify/functions/eb/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200


